### ISSUE TITLE
dva可以配合云函数使用吗？

### ISSUE THREAD

**Issue by easy261925** [zjafei/taro-dva-demo#1]
请教一下，Taro + dva 可以配合云开发使用吗？
可以在 model *函数中使用 call(Taro.cloud.callFunction ...) 这种操作吗？

**Comment by zjafei** [comment]
云函数不是很清楚啊 
大概看了一下云函数只是改变 api 接口形式的
要是这样那就在effect里面使用云函数就可以了

**Comment by easy261925** [comment]
好的，我试试，感谢
